### ISSUE TITLE
Allow no background color for SVG

### ISSUE THREAD

**Issue by tanguilp** [iodevs/qr_code#31]
It'd be nice if the background color was not mandatory, so that the SVG background could be transparent and show to the background of the site (which can have any color).

**Comment by ondrej-tucek** [comment]
Now the transparency will be available via ` %SvgSettings{background_transparency: 0}`

**Comment by tanguilp** [comment]
I suggest using `opacity` instead of `transparency`. This is the term used by SVG specifications. And `background_opacity: 0` means "transparent", while `background_transparency: 0` means the background is absolutely not transparent.

If this is a binary chose (transparent / not transparent), then maybe using a boolean could make more sense? (`transparent_background: true`)

**Comment by ondrej-tucek** [comment]
Thank you for comment. Good point, `opacity` fits better I'll fix it.

Well that's the question :-) On the start I was thinking same a way. I would let that with no binary choose for now (there is bigger scalability of opacity)

**Comment by tanguilp** [comment]
Then why not having a `background-properties` field instead? That would be a key of SVG attributes. That way a user can set whatever he wants.

**Comment by ondrej-tucek** [comment]
I've discussed with @s-m-i-t-a about your proposal and we came with a render functionality (more possibility for user to set what he want). For example: color gradient, put small image on the qr code, etc.

For now I cannot tell you when it'll be done, we haven't much time in these days. Also there is PR with png export waiting on us...
